name: Fullstack To-Do App CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest # Use the official MongoDB Docker image
        ports:
          - 27017:27017
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install backend dependencies and run tests
      run: |
        cd server
        npm install
        npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          # Clone the repository
          rm -rf ~/todo-list-fullstack
          git clone https://github.com/${{ github.repository }}.git ~/todo-list-fullstack
          
          # Navigate to server, install dependencies, and create production env file
          cd ~/todo-list-fullstack/server
          npm install
          echo "PORT=5000" > ./config/prod.env
          echo "MONGODB_URL=mongodb://localhost:27017/todo-app" >> ./config/prod.env
          echo "2c274501988a303627696dbe0f1937ee5d8b5664c36959107f7cd58e89b65ee9" >> ./config/prod.env
          
          # Stop old processes and start backend using npx
          pm2 stop all || true
          pm2 start "npx env-cmd -f ./config/prod.env node index.js" --name "backend" --cwd ~/todo-list-fullstack/server

          
          # Setup and serve frontend on port 80
          cd ~/todo-list-fullstack/client
          npm install
          # The 'serve' package is a dependency in this project, so we don't need to install it globally
          npm run build
          pm2 start "npx serve -s build -l 3000" --name "frontend" --cwd ~/todo-list-fullstack/client 
